Create fr.lua
Qbox-project/qbx_tunerchip pull request #1
Opened 2022-11-06 16:15 UTC by TonybynMp4

yes

2022-11-07 14:00 UTC, YvanCywan approved these changes
C'est bon.

2022-11-07 15:47 UTC, D4isDAVID requested changes

2022-11-07 15:47 UTC, D4isDAVID commented on locales/fr.lua
> +    Lang = Lang or Locale:new({
```suggestion
    Lang = Locale:new({
```
This shouldn't be here.

2022-11-08 02:05 UTC, D4isDAVID approved these changes

2022-11-08 02:14 UTC, merged